version: '3.8'
services:
  api-backend:
    build:
      context: ./api-backend
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_j5GMCDdNE0Uu@ep-super-breeze-axu8gq3l-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    volumes:
      - ./api-backend:/app
    depends_on:
      - db

  admin-web:
    build:
      context: ./admin-web
    ports:
      - "5001:5000"
    environment:
      - FASTAPI_URL=http://api-backend:8000
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./admin-web:/app
    depends_on:
      - api-backend

  mobile-app:
    build:
      context: ./mobile-app
    ports:
      - "8081:8081"
    environment:
      - EXPO_USE_V2_RESOLVER=1
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.27
    volumes:
      - ./mobile-app:/app
      - /app/node_modules
    depends_on:
      - api-backend

  haproxy_proxy:
    image: haproxy:2.9-alpine
    ports:
      - "80:80"
      - "8090:8090"
      - "8404:8404"
      - "8405:8405"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - admin-web
      - api-backend

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - haproxy_proxy

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
