services:
  api-backend:
    build:
      context: ./api-backend
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_j5GMCDdNE0Uu@ep-super-breeze-axu8gq3l-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    volumes:
      - ./api-backend:/app

  admin-web:
    build:
      context: ./admin-web
    ports:
      - "5001:5000"
    environment:
      - FASTAPI_URL=http://api-backend:8000
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./admin-web:/app
    depends_on:
      - api-backend

  mobile-app:
    build:
      context: ./mobile-app
    ports:
      - "8082:8081"
    environment:
      - EXPO_USE_V2_RESOLVER=1
      - EXPO_PUBLIC_API_BASE_URL=http://127.0.0.1:8001
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    volumes:
      - ./mobile-app:/app
      - /app/node_modules
    depends_on:
      - api-backend
