apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # Esta es la URL interna de la red de Docker para llegar a Prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false